version: '3'

services:

  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "8080:80"
  
  crontab:
    build: cron/.
    volumes:
      - data-volume:/var/log/

volumes:
  data-volume:
